// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZJZG6QGcK3vrlGn5VZK3wgJ7mKhOZ4I',
    appId: '1:656477923079:web:3bb4ac94edcb72113707a2',
    messagingSenderId: '656477923079',
    projectId: 'iothome-927b1',
    authDomain: 'iothome-927b1.firebaseapp.com',
    databaseURL: 'https://iothome-927b1-default-rtdb.firebaseio.com',
    storageBucket: 'iothome-927b1.firebasestorage.app',
    measurementId: 'G-CPDX8YVWQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6sihcX1nPwbEVs1SdRXvpeFp8M0pvOB4',
    appId: '1:656477923079:android:c4a39f1e9bc7d8a33707a2',
    messagingSenderId: '656477923079',
    projectId: 'iothome-927b1',
    databaseURL: 'https://iothome-927b1-default-rtdb.firebaseio.com',
    storageBucket: 'iothome-927b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt1ssGpI8EBCwR77rEwM17FJHHaoTMa8g',
    appId: '1:656477923079:ios:aa9c2f4b923cfcaf3707a2',
    messagingSenderId: '656477923079',
    projectId: 'iothome-927b1',
    databaseURL: 'https://iothome-927b1-default-rtdb.firebaseio.com',
    storageBucket: 'iothome-927b1.firebasestorage.app',
    iosBundleId: 'com.example.skripsiHangans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt1ssGpI8EBCwR77rEwM17FJHHaoTMa8g',
    appId: '1:656477923079:ios:aa9c2f4b923cfcaf3707a2',
    messagingSenderId: '656477923079',
    projectId: 'iothome-927b1',
    databaseURL: 'https://iothome-927b1-default-rtdb.firebaseio.com',
    storageBucket: 'iothome-927b1.firebasestorage.app',
    iosBundleId: 'com.example.skripsiHangans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZJZG6QGcK3vrlGn5VZK3wgJ7mKhOZ4I',
    appId: '1:656477923079:web:5d3cf5b2b14655a13707a2',
    messagingSenderId: '656477923079',
    projectId: 'iothome-927b1',
    authDomain: 'iothome-927b1.firebaseapp.com',
    databaseURL: 'https://iothome-927b1-default-rtdb.firebaseio.com',
    storageBucket: 'iothome-927b1.firebasestorage.app',
    measurementId: 'G-J6673D9RE2',
  );
}
